#!/usr/bin/env bash
# Creates a PID file and handles multiple signals
echo $$ > /tmp/myscript.pid
trap "echo I hate the kill command; rm /tmp/myscript.pid; exit" SIGTERM
trap "echo Y u no love me?!" SIGINT
trap "rm /tmp/myscript.pid; exit" SIGQUIT
while true
do
    echo "To infinity and beyond"
    sleep 2
done
