#!/usr/bin/env bash
# Creates a PID file and handles signals with exact output
echo $$ > /tmp/myscript.pid
trap "echo Y U no love me?!" SIGINT
trap "echo I hate the kill command; rm /tmp/myscript.pid; echo OK; exit" SIGTERM
trap "rm /tmp/myscript.pid; echo OK; exit" SIGQUIT
while true
do
    echo "To infinity and beyond"
    sleep 2
done
